<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Arvind-Susdiny" ignored="0" name="Default test" tests="7" failures="1" timestamp="03 Sep 2018 07:22:22 GMT" time="117.558" errors="0">
  <testcase name="tcVerifyPageTitle" time="0.682" classname="com.puma.TC.productselection.TC_Purchase_Of_MenRunningShoes"/>
  <testcase name="loginToappWithrequiredCredentials" time="11.798" classname="com.puma.TC.productselection.TC_Purchase_Of_MenRunningShoes"/>
  <testcase name="tcNavigateTo_Men_RunningShoes" time="4.593" classname="com.puma.TC.productselection.TC_Purchase_Of_MenRunningShoes"/>
  <testcase name="tcClcikOnSecondShoe_AndSwitchToCartPage" time="5.107" classname="com.puma.TC.productselection.TC_Purchase_Of_MenRunningShoes"/>
  <testcase name="tcSelectSizeAndQuantity" time="2.434" classname="com.puma.TC.productselection.TC_Purchase_Of_MenRunningShoes"/>
  <testcase name="tcAddToCartSelectedProduct" time="71.082" classname="com.puma.TC.productselection.TC_Purchase_Of_MenRunningShoes"/>
  <testcase name="tcValidateCartWithProductNamePriceAndQuantity" time="3.256" classname="com.puma.TC.productselection.TC_Purchase_Of_MenRunningShoes">
    <failure type="java.lang.AssertionError" message="expected [1] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.puma.productselection.Purchase_of_MenRunningShoes.validateCartWithProductNamePriceAndQuantity(Purchase_of_MenRunningShoes.java:198)
	at com.puma.TC.productselection.TC_Purchase_Of_MenRunningShoes.tcValidateCartWithProductNamePriceAndQuantity(TC_Purchase_Of_MenRunningShoes.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- tcValidateCartWithProductNamePriceAndQuantity -->
</testsuite> <!-- Default test -->
